services:
  comic-manager:
    image: comic-manager
    ports:
      - "3000:3000"
    volumes:
      - ./comics:/app/comics
    restart: unless-stopped
    depends_on:
      - db

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: comics
      POSTGRES_USER: comicuser
      POSTGRES_PASSWORD: comicpass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
